authors:
  markeyser:
    name: Marcos Keyser
    description: AI engineer & builder of specialized, reliable systems
    avatar: https://github.com/markeyser.png
    url: https://www.linkedin.com/in/markeyser/